spring:
  application:
    name: PROJECT-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/trustwork_project
    username: postgres
    password: postgres

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: c3VwZXJTZWNyZXRLZXlGb3JSZXNvdXJjZU1hbmFnZW1lbnRTeXN0ZW0yMDI0
  expiration: 86400000